### ISSUE TITLE
[QUESTION] Exception 'Symbol' object is not subscriptable

### ISSUE THREAD

**Issue by ankostas** [AishwaryaSivaraman/COMET#1]
Hello! I experience a problem launching the example from the description. On each iteration, it gives me 'Exception 'Symbol' object is not subscriptable'. On your screenshot, it would not happen. Any recommendations? Thank you

**Comment by tjumyk** [comment]
@ankostas Hi, I got this error as well, could you please let me know how you fixed it?

**Comment by ankostas** [comment]
@tjumyk Hello! Yes, just used the earlier optimathsat version. Probably 1.7.1 or 1.7.0.1 should work

**Comment by tjumyk** [comment]
@ankostas thanks a lot!
